/**
 * NyaayaMitra — Chat Turn Builder
 *
 * Every response is AI-generated by Claude. No preset template text.
 * The concierge extracts profile signals, the domain modules provide
 * structured data, and Claude composes the actual reply.
 */

const { buildChatConciergeResponse } = require('./chatConcierge');
const { buildGovernmentLookupPlan } = require('./governmentLookup');
const { buildEntityIdentifierSnapshot, runBusinessAutopilot } = require('./businessAdvisors');
const { buildComplianceManagerPlan, buildLibraryPayload } = require('./sectorCompliance');
const { buildSubmissionPacket } = require('./submissionDesk');
const { getFormsForWorkflow, getFormTemplate, prefillForm, generateFormPackage } = require('./formEngine');
const { askAnthropic, getAiStatus } = require('../services/anthropic');

async function buildChatTurn(input = {}, store) {
  const message = String(input.message || '').trim();

  // Boot greeting — AI generates the welcome message
  if (message === '__BOOT__') {
    return buildBootGreeting();
  }

  const concierge = buildChatConciergeResponse(input, store);
  const autoRunActions = selectAutoRunActions({
    message,
    suggestedActions: concierge.suggestedActions || [],
    collectedProfile: concierge.collectedProfile || {},
    clarificationPrompts: concierge.clarificationPrompts || []
  });

  const toolResults = autoRunActions.map((action) => executeAction(action));

  // Claude generates EVERY reply — no template fallback
  const reply = await composeAIReply({
    input,
    concierge,
    toolResults
  });

  return {
    reply,
    collectedProfile: concierge.collectedProfile || {},
    clarificationPrompts: concierge.clarificationPrompts || [],
    quickFacts: concierge.quickFacts || [],
    suggestedActions: concierge.suggestedActions || [],
    autoRun: toolResults.length > 0,
    toolResults,
    tone: concierge.tone || {}
  };
}

function selectAutoRunActions(context) {
  const message = String(context.message || '');
  const lower = message.toLowerCase();
  const byView = new Map((context.suggestedActions || []).map((item) => [item.view, item]));
  const profile = context.collectedProfile || {};
  const actions = [];

  if (byView.has('government-lookup') && profile.identifierValue) {
    actions.push(byView.get('government-lookup'));
  }

  const hasBusinessType = Boolean(profile.sectorId || profile.businessType);
  const hasLocation = Boolean(profile.city || profile.state);
  const hasStage = Boolean(profile.stage);
  const explicitSubmission = /\b(submit|submission|apply|application|file|packet|form)\b/.test(lower);
  const explicitKnowledge = /\b(source|portal|law|rule|website|library)\b/.test(lower);
  const explicitFormation = /\b(incorporat|startup|new business|din|dsc|director kyc|founder)\b/.test(lower);

  if (byView.has('compliance-manager') && hasBusinessType && (hasLocation || hasStage)) {
    actions.push(byView.get('compliance-manager'));
  }

  if (byView.has('form-filler') && /\b(fill form|fill the form|do it for me|submit for me|prepare my forms|generate form|download form|create application|spice|inc[- ]?32|gst\s*reg|fssai form|dir[- ]?3)\b/.test(lower)) {
    actions.push(byView.get('form-filler'));
  }

  if (byView.has('submissions') && explicitSubmission && (hasBusinessType || /\b(gst|fssai|foscos)\b/.test(lower))) {
    actions.push(byView.get('submissions'));
  }

  if (byView.has('launch') && explicitFormation && !profile.identifierValue) {
    actions.push(byView.get('launch'));
  }

  if (!actions.length && byView.has('library') && explicitKnowledge) {
    actions.push(byView.get('library'));
  }

  if (!actions.length && byView.has('entity-snapshot') && profile.identifierValue) {
    actions.push(byView.get('entity-snapshot'));
  }

  return dedupeByView(actions).slice(0, 3);
}

function executeAction(action) {
  const prefill = action?.prefill || {};

  switch (action?.view) {
    case 'government-lookup':
      return { kind: 'government-lookup', data: buildGovernmentLookupPlan(prefill) };
    case 'entity-snapshot':
      return { kind: 'entity-snapshot', data: buildEntityIdentifierSnapshot(prefill) };
    case 'compliance-manager':
      return { kind: 'compliance-manager', data: buildComplianceManagerPlan(prefill) };
    case 'submissions':
      return { kind: 'submissions', data: buildSubmissionPacket(prefill) };
    case 'launch':
      return { kind: 'launch', data: runBusinessAutopilot(prefill) };
    case 'library':
      return { kind: 'library', data: buildLibraryPayload() };
    case 'form-filler': {
      const workflow = prefill.workflow || '';
      const requestedForms = prefill.requestedForms || [];
      let formIds;
      if (requestedForms.length) {
        formIds = requestedForms;
      } else if (workflow) {
        const wf = getFormsForWorkflow(workflow);
        formIds = (wf.forms || []).map((f) => f.id);
      } else {
        const wf = getFormsForWorkflow('full-launch');
        formIds = (wf.forms || []).map((f) => f.id);
      }
      // Pre-fill the first form (most relevant) with profile data
      const primaryId = formIds[0] || 'spice-plus-a';
      const prefilled = prefillForm(primaryId, prefill);
      const allForms = formIds.map((id) => {
        const tpl = getFormTemplate(id);
        return tpl && !tpl.error ? { id: tpl.id, name: tpl.name, authority: tpl.authority, portalUrl: tpl.portalUrl, fees: tpl.fees, timeline: tpl.timeline } : null;
      }).filter(Boolean);
      return {
        kind: 'form-package',
        data: {
          primaryForm: prefilled,
          allForms,
          workflow: workflow || 'custom',
          totalForms: allForms.length,
          formId: primaryId,
          portalUrl: prefilled.portalUrl || '',
          readyForAiFill: true
        }
      };
    }
    default:
      return null;
  }
}

async function composeAIReply(context) {
  const aiStatus = getAiStatus();
  if (!aiStatus.configured) {
    return 'NyaayaMitra requires an active AI connection to provide personalized compliance guidance. Please configure the ANTHROPIC_API_KEY to enable intelligent responses. Without it, I cannot analyze your specific situation or provide tailored legal and compliance advice.';
  }

  try {
    const prompt = buildIntelligentPrompt(context);
    const result = await askAnthropic({
      prompt,
      maxTokens: 2048,
      temperature: 0.25
    });

    const text = String(result.text || '').trim();
    if (!text) {
      return 'I understood your message but my response generation encountered an issue. Could you try rephrasing or providing more details about what you need?';
    }
    return text;
  } catch (error) {
    const message = error?.message || 'Unknown error';
    if (message.includes('API_KEY')) {
      return 'NyaayaMitra needs an active AI connection. Please ensure the ANTHROPIC_API_KEY is configured correctly.';
    }
    return `I encountered a temporary issue while processing your request: ${message}. Please try again in a moment.`;
  }
}

function buildIntelligentPrompt(context) {
  const userMessage = String(context.input.message || '').trim();
  const profile = context.concierge.collectedProfile || {};
  const toolResults = (context.toolResults || []).filter(Boolean);
  const clarifications = context.concierge.clarificationPrompts || [];
  const quickFacts = context.concierge.quickFacts || [];

  const sections = [];

  // User's actual message
  sections.push(`USER MESSAGE:\n${userMessage}`);

  // Business profile context (what we know so far)
  const profileFacts = [];
  if (profile.businessName) profileFacts.push(`Business name: ${profile.businessName}`);
  if (profile.businessType) profileFacts.push(`Business type: ${profile.businessType}`);
  if (profile.sectorId) profileFacts.push(`Sector: ${profile.sectorId}`);
  if (profile.city) profileFacts.push(`City: ${profile.city}`);
  if (profile.state) profileFacts.push(`State: ${profile.state}`);
  if (profile.stage) profileFacts.push(`Stage: ${profile.stage}`);
  if (profile.employees) profileFacts.push(`Employees: ${profile.employees}`);
  if (profile.entityType) profileFacts.push(`Entity type: ${profile.entityType}`);
  if (profile.identifierType) profileFacts.push(`Identifier type: ${profile.identifierType}`);
  if (profile.identifierValue) profileFacts.push(`Identifier value: ${profile.identifierValue}`);
  if (profile.servesAlcohol === true) profileFacts.push('Serves alcohol: yes');
  if (profile.servesAlcohol === false) profileFacts.push('Serves alcohol: no');
  if (profile.incorporationYear) profileFacts.push(`Incorporation year (inferred): ${profile.incorporationYear}`);
  if (profile.listingStatus) profileFacts.push(`Listing status (inferred): ${profile.listingStatus}`);

  if (profileFacts.length) {
    sections.push(`COLLECTED BUSINESS PROFILE:\n${profileFacts.join('\n')}`);
  } else {
    sections.push('COLLECTED BUSINESS PROFILE: No facts collected yet — this is likely the user\'s first message.');
  }

  // Tool results (structured data from domain modules)
  if (toolResults.length) {
    const toolSummaries = toolResults.map((item) => {
      if (!item?.data) return '';
      const kind = item.kind;
      const data = item.data;

      if (kind === 'government-lookup') {
        return `GOVERNMENT LOOKUP RESULT:\nSummary: ${data.summary || 'N/A'}\nIdentity: ${JSON.stringify(data.identity || {})}\nOfficial checks to run: ${JSON.stringify((data.officialChecks || []).map(c => c.label))}\nRecords still needed: ${JSON.stringify(data.recordsStillNeeded || [])}`;
      }
      if (kind === 'entity-snapshot') {
        return `ENTITY SNAPSHOT:\nSummary: ${data.summary || 'N/A'}\nStatus board: ${JSON.stringify((data.statusBoard || []).slice(0, 6))}`;
      }
      if (kind === 'compliance-manager') {
        return `COMPLIANCE ANALYSIS:\nSummary: ${data.summary || 'N/A'}\nAction plan (${(data.actionPlan || []).length} items): ${JSON.stringify((data.actionPlan || []).slice(0, 8).map(a => ({ title: a.title, priority: a.priority, authority: a.authority })))}\nCritical stops: ${JSON.stringify(data.criticalStops || [])}\nDimension coverage: ${JSON.stringify((data.dimensionCoverage || []).slice(0, 10))}`;
      }
      if (kind === 'submissions') {
        return `SUBMISSION PACKET:\nTitle: ${data.title || 'N/A'}\nAuthority: ${data.authority || 'N/A'}\nPortal: ${data.portalUrl || 'N/A'}\nForms: ${data.forms || 'N/A'}\nDocuments required: ${data.documentsRequired || 'N/A'}`;
      }
      if (kind === 'launch') {
        return `LAUNCH AUTOPILOT:\nSummary: ${data.summary || 'N/A'}\nWorkstreams (${(data.workstreams || []).length}): ${JSON.stringify((data.workstreams || []).map(w => w.title))}\nBlockers: ${JSON.stringify(data.blockers || [])}`;
      }
      if (kind === 'form-package') {
        const primary = data.primaryForm || {};
        const allNames = (data.allForms || []).map(f => f.name);
        const summary = primary.prefillSummary || {};
        return `FORM PACKAGE PREPARED:\nPrimary form: ${primary.name || data.formId}\nAll forms in sequence: ${JSON.stringify(allNames)}\nTotal forms: ${data.totalForms}\nFields pre-filled from profile: ${summary.filledFromProfile || 0}\nTotal fields: ${summary.totalFields || '?'}\nProfile completeness: ${summary.profileCompleteness || '?'}\n\nIMPORTANT: The form engine has prepared downloadable form templates. Tell the user what forms are ready, what information is still needed to fill them completely, and that they can click "Fill Form" on the form cards below to enter missing details. Then they can download the filled form as a print-ready document or use it as a reference when filling the portal. Ask for any missing critical details like director names, PAN, address etc. so AI can fill them accurately.`;
      }
      return '';
    }).filter(Boolean);

    if (toolSummaries.length) {
      sections.push(`STRUCTURED DATA FROM ANALYSIS ENGINES:\n${toolSummaries.join('\n\n')}`);
    }
  }

  // What we still need from the user
  if (clarifications.length) {
    const missing = clarifications.map(c => c.question).join('; ');
    sections.push(`INFORMATION GAPS (ask naturally if relevant):\n${missing}`);
  }

  // Form request context
  const hasFormRequest = toolResults.some((item) => item?.kind === 'form-package');
  const formInstructions = hasFormRequest ? `
11. FORM FILLING: The system has prepared government forms for the user. Explain which forms are ready and what data is still needed. Ask for missing details like:
    - Director full names (as on PAN card), dates of birth, PAN numbers
    - Registered office full address with PIN code
    - Authorized share capital and paid-up capital amounts
    - Business activity description and NIC code
    - Bank account details for GST/EPFO registration
    - Mobile numbers and email addresses (unique per director for DIN)
    Tell the user they can click "Fill Form" on any form card to enter details, then "Download" to get a print-ready copy or use it as reference on the government portal. Be proactive — if you can infer any field values from the conversation, mention what you've already filled.
12. When the user provides details (names, PAN, address, etc.), acknowledge what you received and explain which form fields those fill. Guide them through remaining gaps.` : '';

  // Instructions for the AI
  sections.push(`INSTRUCTIONS:
Respond directly to the user's message. Use the collected profile and analysis data above to give specific, actionable advice.

Rules:
1. NEVER use generic or templated language. Every response must be specifically tailored to this user's exact situation.
2. If structured data was provided above, weave the key findings into your natural response. Don't just repeat the data — interpret it, prioritize it, and explain what matters most.
3. If there are information gaps, ask for the missing facts naturally within your response — don't present them as a separate questionnaire.
4. Always cite specific Indian laws, section numbers, form numbers, and portal URLs when relevant.
5. Always mention real deadlines and penalties when applicable.
6. If an identifier was provided, explain exactly what you can infer from its structure and what still requires official portal verification.
7. Be warm, direct, and authoritative — like a trusted advisor who knows Indian compliance deeply.
8. Keep the response focused. Don't dump everything at once. Prioritize what's most urgent or relevant to what the user asked.
9. NEVER say things like "I've analyzed your situation and here's what I found" — just give the advice directly.
10. When mentioning government portals, always include the actual URL.${formInstructions}`);

  return sections.join('\n\n');
}

async function buildBootGreeting() {
  const aiStatus = getAiStatus();
  let reply = 'Welcome to NyaayaMitra. Tell me about your business — what it does, where it is, and what compliance or legal question you need help with.';

  if (aiStatus.configured) {
    try {
      const result = await askAnthropic({
        prompt: `Generate a warm, professional welcome message for NyaayaMitra — India's AI compliance advisor. The user just opened the app for the first time.

In 2-3 sentences, invite them to:
- Tell you about their business (what it does, where it's located)
- Paste any business identifier they have (CIN, GSTIN, Udyam number)
- Ask any compliance, legal, or regulatory question
- Upload any documents they already have

Make it feel like talking to a brilliant advisor who genuinely wants to help, not like reading a product manual. Be warm but professional. Don't use bullet points — write naturally.

Today's date is ${new Date().toISOString().slice(0, 10)}.`,
        maxTokens: 300,
        temperature: 0.5
      });
      if (result.text) reply = result.text;
    } catch (_error) {
      // Use the minimal fallback above
    }
  }

  return {
    reply,
    collectedProfile: {},
    clarificationPrompts: [],
    quickFacts: [],
    suggestedActions: [],
    autoRun: false,
    toolResults: [],
    tone: {}
  };
}

function dedupeByView(items) {
  const seen = new Set();
  return items.filter((item) => {
    if (!item?.view || seen.has(item.view)) return false;
    seen.add(item.view);
    return true;
  });
}

module.exports = {
  buildChatTurn
};
