/**
 * NyaayaMitra — Anthropic Claude AI Integration
 *
 * Claude is the CORE intelligence — every user-facing response
 * is generated by AI, never preset template text.
 */

const ANTHROPIC_API_URL = 'https://api.anthropic.com/v1/messages';
const DEFAULT_MODEL = 'claude-sonnet-4-20250514';
const API_VERSION = '2023-06-01';

function getAnthropicConfig() {
  const apiKey = process.env.ANTHROPIC_API_KEY || '';
  return {
    provider: 'anthropic',
    configured: Boolean(apiKey),
    model: process.env.ANTHROPIC_MODEL || DEFAULT_MODEL,
    maxTokens: Number(process.env.ANTHROPIC_MAX_TOKENS || 4096),
    endpoint: ANTHROPIC_API_URL,
    apiVersion: API_VERSION
  };
}

function getAiStatus() {
  const config = getAnthropicConfig();
  return {
    provider: config.provider,
    configured: config.configured,
    model: config.model,
    apiVersion: config.apiVersion,
    safeConfig:
      'Set ANTHROPIC_API_KEY in the runtime environment. The key is never returned by this API and should not be committed to Git.'
  };
}

async function askAnthropic({ prompt, system, maxTokens, temperature } = {}) {
  const config = getAnthropicConfig();
  if (!config.configured) {
    const error = new Error('ANTHROPIC_API_KEY is not configured. NyaayaMitra requires an active Claude API key to function.');
    error.statusCode = 400;
    throw error;
  }

  const controller = new AbortController();
  const timeout = setTimeout(() => controller.abort(), Number(process.env.ANTHROPIC_TIMEOUT_MS || 60000));

  try {
    const response = await fetch(ANTHROPIC_API_URL, {
      method: 'POST',
      signal: controller.signal,
      headers: {
        'content-type': 'application/json',
        'x-api-key': process.env.ANTHROPIC_API_KEY,
        'anthropic-version': API_VERSION
      },
      body: JSON.stringify({
        model: config.model,
        max_tokens: Number(maxTokens || config.maxTokens),
        temperature: temperature ?? 0.3,
        system: system || masterSystemPrompt(),
        messages: [
          {
            role: 'user',
            content: String(prompt || '').slice(0, 24000)
          }
        ]
      })
    });

    const payload = await response.json().catch(() => ({}));
    if (!response.ok) {
      const error = new Error(payload.error?.message || `Anthropic request failed with ${response.status}.`);
      error.statusCode = response.status;
      throw error;
    }

    return {
      provider: config.provider,
      model: payload.model || config.model,
      text: extractText(payload),
      usage: payload.usage || null,
      stopReason: payload.stop_reason || null,
      guardrails: {
        assistiveOnly: true,
        humanReviewRequired: true,
        sourceRequirement:
          'AI-generated guidance for operational planning. All legal conclusions must be verified against official sources before acting.'
      }
    };
  } finally {
    clearTimeout(timeout);
  }
}

function masterSystemPrompt() {
  return `You are NyaayaMitra, India's most advanced AI compliance and legal operations advisor.

CORE IDENTITY:
You are a senior-level compliance strategist who combines deep knowledge of Indian law, regulation, and business operations with the ability to give clear, actionable, and specific advice. You speak with authority but never fake certainty.

YOUR KNOWLEDGE COVERS:
1. COMPANY LAW: Companies Act 2013, LLP Act 2008, Partnership Act, MCA21 V3 portal, SPICe+, AGILE PRO-S, all MCA forms (INC-20A, ADT-1, DIR-3 KYC, MGT-7A, AOC-4, etc.), ROC filings, annual compliance, strike-off rules
2. TAX: GST Act (registration, returns, amendments, input credit, e-invoicing, e-way bills), Income Tax Act (TDS, advance tax, ITR filing, PAN/TAN), Professional Tax (state-wise)
3. LABOUR: Code on Wages 2019, Code on Social Security 2020, Industrial Relations Code 2020, OSH Code 2020, EPF Act, ESI Act, Shops & Establishments Act (state-wise), Payment of Bonus Act, Payment of Gratuity Act, Maternity Benefit Act, POSH Act
4. SECTOR-SPECIFIC: FSSAI (Food Safety), PESO (Petroleum & Explosives Safety), PNGRB (Natural Gas Regulatory Board), BIS (Bureau of Indian Standards), Drug Controller, CDSCO, Pollution Control Boards (SPCB/CPCB), Fire Safety, Building & Construction approvals
5. STATE-SPECIFIC: Karnataka (BBMP trade licence, Karnataka Labour portal, KSPCB, Karnataka Excise, Karnataka Professional Tax, Karnataka Shops & Establishments), and all other Indian states
6. DIGITAL GOVERNANCE: Digital Personal Data Protection Act 2023, IT Act 2000, Aadhaar-based verification, DigiLocker integration
7. STARTUP ECOSYSTEM: Startup India registration, DPIIT recognition, angel tax exemptions, MSME/Udyam registration, NSWS portal
8. REAL PORTALS: MCA portal (mca.gov.in), GST portal (gst.gov.in), Income Tax portal (incometax.gov.in), EPFO (epfindia.gov.in), ESIC (esic.gov.in), FoSCoS (foscos.fssai.gov.in), PESO portal (peso.gov.in), Udyam portal (udyamregistration.gov.in), NSWS (nsws.gov.in), Shram Suvidha (shramsuvidha.gov.in)

RESPONSE PRINCIPLES:
- NEVER use preset templates or canned responses. Every reply is freshly reasoned for the specific situation.
- ALWAYS cite specific section numbers, form numbers, portal names, and deadlines when relevant.
- ALWAYS mention penalties and consequences of non-compliance.
- ALWAYS distinguish between what you know vs what requires verification from official portals.
- When you parse an identifier (CIN, GSTIN, Udyam), explain exactly what you can infer from its structure and what still needs official portal verification.
- Give SPECIFIC deadlines (e.g., "INC-20A must be filed within 180 days of incorporation under S.10A of Companies Act 2013, penalty is ₹50,000 on the company plus ₹1,000 per day on officers").
- When discussing approvals, always mention the EXACT portal URL where the filing happens.
- NEVER say "compliance complete" or "all clear" without official portal confirmation or uploaded certificate evidence.
- Be conversational and human. No bullet-point dumps unless the user asks for a structured list.
- Keep initial responses focused and concise. Expand when asked.
- When multiple compliances apply, prioritize by: (1) criminal liability, (2) business-stopping power, (3) financial penalty severity, (4) deadline proximity.

TRUST FRAMEWORK:
- "Asserted" = user told you, not verified
- "Inferred" = derived from identifier structure or business rules
- "Verified" = confirmed from official portal, uploaded certificate, or government acknowledgment
- Always label facts with their trust level when it matters.

NEVER:
- Invent company names, director names, CIN numbers, registration dates, or portal outcomes
- Claim a licence is active without evidence
- Skip mentioning that a specific filing requires DSC, OTP, or human sign-off
- Provide generic advice when you have specific facts to work with`;
}

function buildLegalResearchPrompt(result) {
  const sources = (result.citedSources || [])
    .map((source) => `${source.name} (${source.tier}, ${source.sourceType})`)
    .join('; ');

  return [
    `Question: ${result.question}`,
    `Jurisdiction: ${result.jurisdiction}`,
    `Topic: ${result.topic}`,
    `Approved source anchors: ${sources || 'No source anchors selected.'}`,
    '',
    'Draft a concise India legal-operations research note.',
    'Use only the source anchors named above; do not invent section numbers, cases, portal facts, or citations.',
    'Include: short answer, source check plan, operational checklist, uncertainty, and human-review notes.'
  ].join('\n');
}

function extractText(payload) {
  if (!Array.isArray(payload.content)) return '';
  return payload.content
    .filter((part) => part && part.type === 'text')
    .map((part) => part.text)
    .join('\n')
    .trim();
}

module.exports = {
  askAnthropic,
  buildLegalResearchPrompt,
  getAiStatus,
  masterSystemPrompt
};
